const typography = {
  letterSpacings: {
    tighter: "-0.05em",
    tight: "-0.025em",
    normal: "normal",
    wide: "0.025em",
    wider: "0.05em",
    widest: "0.1em",
  },
  lineHeights: {
    normal: "normal",
    standard: "1.4rem",
    none: "1rem",
    shorter: "1.25rem",
    short: "1.375rem",
    base: "1.5rem",
    tall: "1.625rem",
    taller: "2rem",
    "18": "1.125rem",
    "24": "1.5rem",
    "30": "1.875rem",
    "36": "2.25rem",
    "48": "3rem",
    "72": "4.5rem",
  },
  fontWeights: {
    hairline: 100,
    extraLight: 200,
    light: 300,
    normal: "normal",
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
  },
  fonts: {
    //heading: `-apple-system, BlinkMacSystemFont, "Open Sans",sans-serif,"Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    //body: `-apple-system, "Open Sans",sans-serif,Montserrat`,
    heading: `"Open Sans"`,
    body: `"Open Sans"`,
    mono: `SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace`,
  },
  fontSizes: {
    xxs: "0.625rem",
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.125rem",
    lgx: "1.25rem",
    xl: "1.5rem",
    "2md": "2rem",
    "2xl": "3rem",
    "3xl": "4.5rem",
    "4xl": "6rem",
    "5xl": "7.5rem",
    "6xl": "9rem",
  },
};

export default typography;
